okuruchimas/sharm-el-sheikh-strapi

- src/api/company-promotion-card/content-types/company-promotion-card/schema.json
- src/api/service/content-types/service/schema.json
- types/generated/contentTypes.d.ts
add averageRating totalComments and services to company card
> add averageRating totalComments and services to company card

- src/api/company-promotion-card/content-types/company-promotion-card/schema.json
- src/api/event-card/content-types/event-card/schema.json
- types/generated/contentTypes.d.ts
add slug to company and event card
> add slug to colection types to be feched

- config/middlewares.ts
> update cors options

- config/middlewares.ts
> Revert middlewares changes

- src/api/comment/content-types/comment/schema.json
- src/api/comment/controllers/comment.ts
- src/api/comment/routes/comment.ts
- src/api/comment/services/comment.ts
- src/api/company-promotion-card/content-types/company-promotion-card/schema.json
- src/api/company-promotion-card/controllers/company-promotion-card.ts
- src/api/company-promotion-card/routes/custom-routes.ts
- types/generated/contentTypes.d.ts
company card comments, custom route and handler
> company card comments, custom route and handler

- src/api/company-promotion-card/controllers/company-promotion-card.ts
> change add comment response

- src/api/event-card/content-types/event-card/schema.json
- types/generated/contentTypes.d.ts
> change fields order in events card

- src/api/event-card/content-types/event-card/schema.json
- types/generated/contentTypes.d.ts
> fix event card image

- src/api/area/content-types/area/schema.json
- src/api/area/controllers/area.ts
- src/api/area/routes/area.ts
- src/api/area/services/area.ts
- src/api/category/content-types/category/schema.json
- src/api/category/controllers/category.ts
- src/api/category/routes/category.ts
- src/api/category/services/category.ts
- src/api/company-promotion-card/content-types/company-promotion-card/schema.json
- types/generated/contentTypes.d.ts
add area and category to company card
> add area and category to company card

- src/api/area/content-types/area/schema.json
- types/generated/contentTypes.d.ts
> remove localized from area key

- src/api/animator/content-types/animator/schema.json
- src/api/animator/controllers/animator.ts
- src/api/animator/routes/animator.ts
- src/api/animator/routes/custom-routes.ts
- src/api/animator/services/animator.ts
- src/api/comment/content-types/comment/schema.json
- src/api/language/content-types/language/schema.json
- src/api/language/controllers/language.ts
- src/api/language/routes/language.ts
- src/api/language/services/language.ts
- src/components/components/entertainment-service.json
- src/components/helpers/string-array.json
- src/utils/commentHandler.ts
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
feat: animator card with comments, 
languages,
refator adding comment
> feat: animator card with comments, add comment refactor

- src/api/comment/content-types/comment/schema.json
- src/api/language/content-types/language/schema.json
- src/api/taxi-driver/content-types/taxi-driver/schema.json
- src/api/taxi-driver/controllers/taxi-driver.ts
- src/api/taxi-driver/routes/custom-routes.ts
- src/api/taxi-driver/routes/taxi-driver.ts
- src/api/taxi-driver/services/taxi-driver.ts
- src/api/taxi-service/content-types/taxi-service/schema.json
- src/api/taxi-service/controllers/taxi-service.ts
- src/api/taxi-service/routes/taxi-service.ts
- src/api/taxi-service/services/taxi-service.ts
- src/components/components/work-schedule.json
- src/components/helpers/time-slot.json
- src/utils/commentHandler.ts
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
also fix bug while editing comment
> feat: taxi driver

- src/api/taxi-driver/content-types/taxi-driver/schema.json
- types/generated/contentTypes.d.ts
make social links not localizable and be required
> fix: taxi driver

- src/api/club/content-types/club/schema.json
- types/generated/contentTypes.d.ts
> add image to club

- src/api/medication/content-types/medication/schema.json
- types/generated/contentTypes.d.ts
> fix: add slug to medications

- src/api/hotspots-page/content-types/hotspots-page/schema.json
- types/generated/contentTypes.d.ts
> map title hotspots page

- src/components/header/navigation-menu.json
- types/generated/components.d.ts
> add image to nav menu

- src/api/home/content-types/home/schema.json
- src/components/components/home-nav-menu.json
- src/components/header/navigation-menu.json
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
> home nav menu

- src/api/area/content-types/area/schema.json
- src/api/category/content-types/category/schema.json
- src/api/comment/content-types/comment/schema.json
- src/api/company/content-types/company/schema.json
- src/api/company/controllers/company.ts
- src/api/company/routes/company.ts
- src/api/company/routes/custom-routes.ts
- src/api/company/services/company.ts
- src/api/service/content-types/service/schema.json
- src/components/components/company-page-fields.json
- src/components/components/company-schedule.json
- src/components/components/discount.json
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
create company collection type
> feat: company collection type

- src/api/company/content-types/company/schema.json
- types/generated/contentTypes.d.ts
> fix company

- src/api/area/content-types/area/schema.json
- src/api/category/content-types/category/schema.json
- src/api/company/content-types/company/schema.json
- types/generated/contentTypes.d.ts
> fix default values

- src/api/event-card/content-types/event-card/schema.json
- types/generated/contentTypes.d.ts
> add position to events

- src/api/animation-company/content-types/animation-company/schema.json
- src/api/animation-company/controllers/animation-company.ts
- src/api/animation-company/routes/custom-routes.ts
- src/api/animator/content-types/animator/schema.json
- src/api/company/content-types/company/schema.json
- src/components/helpers/text-with-title.json
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
add WC field to company
add company relation to Animator
add new fields to Animation Company
> animation company changes, update company and animator

- src/api/advertisement/content-types/advertisement/schema.json
- src/api/advertisement/controllers/advertisement.ts
- src/api/advertisement/routes/advertisement.ts
- src/api/advertisement/services/advertisement.ts
> feat: adverttisements

- src/api/company-info-page/content-types/company-info-page/schema.json
- src/components/helpers/location-with-name.json
- types/generated/components.d.ts
- types/generated/contentTypes.d.ts
> fix: company info page
